F=raw/hilton/dt/familia/r2/fondos; P=raw/hilton/dt/familia/r1; O=raw/hilton/dt/familia/r2
KEEP="Image 1 is a REAL photograph of the DoubleTree hotel: keep it exactly as it is — same room, walls, furniture, bedding, lamps, window, colors, light and camera framing. Do not redesign, restyle, re-light or move anything in it. Only add the people into this exact scene, with their shadows and lighting matching the photo."
WHO="The people are the family from the references: the mother (image 2), the father (image 3), the daughter about 9 (image 4) and the son about 7 (image 5); keep their faces, hair and ages exactly."
NAT="Candid documentary moment, as if photographed without them noticing. Natural relaxed expressions: soft genuine smiles, eyes looking at each other or at what they are doing, NOT at the camera; natural eye moisture and catchlights from the window, slightly asymmetric faces, relaxed eyelids, no exaggerated open-mouth laughing, no posing, no stock-photo look. Real skin texture, natural hair flyaways, realistic hands with five fingers. Casual weekend clothes in soft neutral and warm tones. Photorealistic, 35mm lens, same exposure and grain as the original photo."
run(){ py scripts/magnific.py seedream "$KEEP $WHO $2 $NAT" --refs $F/$1.jpg $P/mama-D.png $P/papa-A.png $P/nina-B.png $P/nino-A.png --aspecto carrusel --out $O/$1.png > $O/$1.log 2>&1; }
run hab-2camas "Scene: the kids sit cross-legged on the nearer bed in pajamas choosing a movie on a tablet together, the mother sits on the edge of the bed leaning in beside them, the father sits on the second bed smiling watching them. People occupy the lower half of the frame." &
run hab-sep26 "Scene: late afternoon arrival; the son lies on his stomach on the bed with his feet up, the daughter sits next to him showing him something, the mother unpacks a small suitcase on the bench at the foot of the bed looking at them with a soft smile, the father stands near the window. People in the lower half, the lamp and wall remain visible above." &
run restaurante "Scene: family breakfast at one of the tables in the middle ground: the father pours orange juice for the daughter, the son takes a bite of a croissant, the mother holds a coffee cup and looks at the son with a warm smile. Plates with fruit, bread and eggs on the table. The rest of the restaurant stays empty and unchanged." &
run lobby "Scene: check-in arrival walking through the lobby toward the camera in the middle ground: the father pulls a rolling suitcase, the son holds the mother's hand and looks around amazed, the daughter walks ahead carrying a small backpack. Relaxed walking, natural motion." &
wait; tail -qn1 $O/*.log
