BASE="Professional photographic character reference sheet, 3 rows x 4 columns grid on a seamless light grey studio background, soft even studio lighting, ultra realistic candid photography, real skin texture with visible pores and natural imperfections, not airbrushed, not CGI, shot on 85mm. The same single person in all 12 panels, consistent identity. Wearing a plain heather grey crew-neck t-shirt, grey trousers and grey shoes, no logos, no accessories. Row 1 head and shoulders: front, three-quarter, side profile, back of head. Row 2 head and shoulders expressions: neutral, gentle smile, genuine laughing, listening attentively. Row 3 full body, head to toe, feet fully visible inside the frame with floor space below: front, three-quarter, side profile, back."
ADULT_AGE="Age by features: fresh rested face of a 38-year-old, smooth forehead, firm jawline, no under-eye bags, only very faint smile lines, clearly late thirties and NOT in the forties."
LATINO="Chilean, clearly Latin American and NOT Nordic, NOT Scandinavian, slightly rounded facial structure, nose slightly wider than a Nordic type."
M1="Subject: a Chilean mother, of Spanish descent, light skin with warm golden undertone, $LATINO Warm dark brown eyes, natural brows. Shoulder-length dark chestnut brown hair with soft natural waves and subtle warm caramel highlights. Light natural makeup, tiny stud earrings. Warm, approachable, everyday mom. $ADULT_AGE"
M2="Subject: a Chilean mother, of Spanish and Italian descent, light skin with warm golden undertone, $LATINO Hazel-brown eyes. Long straight medium-brown hair past the shoulders with soft honey highlights, center part. Light natural makeup. Friendly, relaxed, everyday mom, slim average build. $ADULT_AGE"
P1="Subject: a Chilean father, of Spanish descent, light skin with warm golden undertone, $LATINO Dark brown eyes. Short dark brown hair, neatly cut, slightly longer on top, short well-groomed stubble beard. Average athletic build, 1.78 m. Warm, easygoing dad. $ADULT_AGE"
P2="Subject: a Chilean father, of Spanish and German descent, light skin with warm golden undertone, $LATINO Light brown eyes. Short medium-brown hair with a side part, clean-shaven with light five o'clock shadow. Average build, 1.80 m. Kind, easygoing dad. $ADULT_AGE"
N1="Subject: a Chilean girl, 10 years old, child proportions, of Spanish descent, light skin with warm golden undertone, clearly Latin American and NOT Nordic. Dark brown eyes, long chestnut brown hair in a loose low ponytail with a few loose strands, one missing-free natural smile with slightly uneven adult front teeth. Cheerful, natural child, no makeup."
N2="Subject: a Chilean girl, 9 years old, child proportions, of Spanish descent, light skin with warm golden undertone, clearly Latin American and NOT Nordic. Brown eyes, shoulder-length light chestnut wavy hair loose, a few freckles on the nose. Curious, cheerful natural child, no makeup."
H1="Subject: a Chilean boy, 7 years old, child proportions, of Spanish descent, light skin with warm golden undertone, clearly Latin American and NOT Nordic. Dark brown eyes, short tousled dark brown hair, round cheeks. Playful, energetic natural child."
H2="Subject: a Chilean boy, 6 years old, child proportions, of Spanish descent, light skin with warm golden undertone, clearly Latin American and NOT Nordic. Brown eyes, short medium-brown hair slightly messy with a cowlick, gap in front baby teeth. Playful, cheeky natural child."
run(){ py scripts/magnific.py seedream "$2 $BASE" --aspecto feed --out raw/hilton/dt/familia/r1/$1.png > raw/hilton/dt/familia/r1/$1.log 2>&1; }
run mama-B "$M1" & run mama-C "$M2" & run papa-A "$P1" & run papa-B "$P2" & run nina-A "$N1" & run nina-B "$N2" & run nino-A "$H1" & run nino-B "$H2" & wait
tail -n2 raw/hilton/dt/familia/r1/*.log
